import {loginPage} from "../../support/pageObject/loginPage";

describe('TestUserAddEditDelete', () => {
    beforeEach(() => {
        loginPage.openLoginPage()
        loginPage.inputUser()
        loginPage.inputPass()
        loginPage.clickLoginButton()
        loginPage.acceptCoockies()
    })

    it('Add a User', () => {
//The main page should be visible
        cy.get('.css-czc5e9 > :nth-child(1) > .MuiGrid-item > .MuiButtonBase-root').click()
        cy.get('[href="/assets"] > .MuiGrid-root > .MuiTypography-root').click()
        cy.get('.css-1d7v3j3 > .MuiGrid-item > .MuiButton-root').click()
        //Choose Assets -> Accounts
        //Automation account should be visible
        cy.get('.MuiList-root > [tabindex="0"]').click()
        //Choose Users tab
        cy.get(':nth-child(4) > :nth-child(5) > .css-1q2ebru > .css-17eim5l').click()
        cy.get('[aria-label="Add"] > .MuiButtonBase-root').click()
        //Check all the fields
        cy.get('.css-kspudp > .MuiGrid-container').should('contain.text','Add User')
        cy.get('.css-1dnniyh').should('contain.text','Cancel')
        cy.get('.css-2l42up > :nth-child(1) > .MuiTypography-root').should('contain.text','User is active')
        cy.get('.css-2l42up > :nth-child(2) > .MuiTypography-root').should('contain.text','User is locked')
        cy.get('.css-2l42up > :nth-child(3) > .MuiTypography-root').should('contain.text','Send Welcome Email')
        cy.get('.css-2l42up > :nth-child(4) > .MuiTypography-root').should('contain.text','User will self activate')
        cy.get('input').eq(3).should('not.have.class', 'Mui-checked')
        cy.get('input').eq(5).should('not.have.class', 'Mui-checked')
        cy.get('input').eq(6).should('be.checked')
        cy.get('input').eq(7).should('not.have.class', 'Mui-checked')
        cy.get('legend').eq(3).should('contain.text','Password')
        cy.get('legend').eq(4).should('contain.text','Retype password')
        cy.get('legend').eq(5).should('contain.text','First Name')
        cy.get('legend').eq(6).should('contain.text','Last Name')
        cy.get('legend').eq(7).should('contain.text','Phone')
        cy.get('legend').eq(8).should('contain.text','Mobile')
        cy.get('legend').eq(9).should('contain.text','Address 1')
        cy.get('legend').eq(10).should('contain.text','Address 2')
        cy.get('legend').eq(11).should('contain.text','City')
        cy.get('legend').eq(12).should('contain.text','State')
        cy.get('legend').eq(13).should('contain.text','Zip')
        cy.get('legend').eq(14).should('contain.text','Country')
        cy.get('legend').eq(15).should('contain.text','Timezone')
        cy.get('legend').eq(16).should('contain.text','Preferred Language')
        cy.get('legend').eq(17).should('contain.text','Title')
        cy.get('legend').eq(18).should('contain.text','Department')
        cy.get('legend').eq(19).should('contain.text','Supervisor')
        cy.get('legend').eq(20).should('contain.text','Notes')
        cy.get('legend').eq(21).should('contain.text','Billing Code')
        //Check the password text
        cy.get(':nth-child(2) > .MuiGrid-root > .MuiBox-root').should('contain.text','Password must have')
        cy.get('ul > :nth-child(1)').should('contain.text','At least One number')
        cy.get('ul > :nth-child(2)').should('contain.text','At least One uppercase latin character')
        cy.get('ul > :nth-child(3)').should('contain.text','At least One lowercase latin character')
        cy.get('ul > :nth-child(4)').should('contain.text','At least One special character')
        cy.get('ul > :nth-child(5)').should('contain.text','8 characters minimum')
        //Add the User's data
        cy.get('input').eq(3).type('testautocy+3@gmail.com')
        cy.get('input').eq(4).click()
        cy.get('input').eq(7).type('123Qwe!qwe')
        cy.get('input').eq(8).type('123Qwe!qwe')
        cy.get('input').eq(9).type('Test')
        cy.get('input').eq(10).type('Auto')
        cy.get('input').eq(11).type('2345432345')
        cy.get('input').eq(12).type('9090909090')
        cy.get('input').eq(13).type('My address 1')
        cy.get('input').eq(14).type('My address 2')
        cy.get('input').eq(15).type('My City 1')
        cy.get('input').eq(16).type('123')
        cy.get('input').eq(17).type('2')
        cy.get(':nth-child(6) > :nth-child(1) > .MuiFormControl-root > .MuiOutlinedInput-root > .MuiSelect-select').click()
        cy.get('[data-value="United States"]').click({force:true})
        cy.get('body').click()
        cy.get(':nth-child(6) > :nth-child(2) > .MuiFormControl-root > .MuiOutlinedInput-root > .MuiSelect-select').click()
        cy.get('[data-value="(UTC-06:00) Easter Island"]').click({force:true})
        cy.get('body').click()
        cy.get(':nth-child(7) > .MuiGrid-root > .MuiFormControl-root > .MuiOutlinedInput-root > .MuiSelect-select').click()
        cy.get('[data-value="de-DE"]').click({force:true})
        cy.get('body').click()
        cy.get('input').eq(21).type('Developer')
        cy.get('input').eq(22).type('New Department')
        cy.get('input').eq(23).type('No New Supervisor')
        cy.get(':nth-child(10) > .MuiGrid-root > .MuiFormControl-root > .MuiOutlinedInput-root').type('Notes are hidden')
        cy.get('input').eq(24).type('555')
        cy.get(':nth-child(2) > .MuiButtonBase-root > .MuiFormLabel-root').click()
        cy.get(':nth-child(1) > .MuiOutlinedInput-root > .MuiSelect-select').click()
        cy.get('[data-value="8"]').click({force:true})
        cy.get('.css-z7g8xj').click()
        cy.get('.css-1orwh6x').should('contain.text','testautocy+3@gmail.com')
        cy.contains('testautocy+3@gmail.com').click()
        //Check that all fields are filled correctly
        cy.get('.css-kspudp > .MuiGrid-container').should('contain.text','Edit User')
        cy.get('.css-z7g8xj').should('contain.text','Save')
        cy.get('.css-1dnniyh').should('contain.text','Cancel')
        cy.get('.MuiGrid-direction-xs-column > :nth-child(2) > .MuiButton-root').should('contain.text','Resend Welcome Email')
        cy.get('.MuiGrid-direction-xs-column > :nth-child(3) > .MuiButton-root').should('contain.text','Reset Password')
        cy.get('input').eq(4).should('contain.value','testautocy+3@gmail.com')
        cy.get('input').eq(5).should('be.checked')
        cy.get('input').eq(3).should('not.have.class', 'Mui-checked')
        cy.contains('User is active').should('be.visible')
        cy.contains('User is locked').should('be.visible')
        cy.get('input').eq(7).should('contain.value','Test')
        cy.get('input').eq(8).should('contain.value','Auto')
        cy.get('input').eq(9).should('contain.value','2345432345')
        cy.get('input').eq(10).should('contain.value','9090909090')
        cy.get('input').eq(11).should('contain.value','My address 1')
        cy.get('input').eq(12).should('contain.value','My address 2')
        cy.get('input').eq(13).should('contain.value','My City 1')
        cy.get('input').eq(14).should('contain.value','123')
        cy.get('input').eq(15).should('contain.value','2')
        cy.get('input').eq(19).should('contain.value','Developer')
        cy.get('input').eq(20).should('contain.value','New Department')
        cy.get('input').eq(21).should('contain.value','No New Supervisor')
        //cy.get(':nth-child(10) > .MuiGrid-root > .MuiFormControl-root > .MuiOutlinedInput-root').should('contain.value','Notes are hidden')
        cy.get('input').eq(22).should('contain.value','555')
        cy.get('.MuiTabs-flexContainer > :nth-child(2) > .MuiButtonBase-root').click()
        cy.get(':nth-child(1) > .MuiOutlinedInput-root > .MuiSelect-select').should('contain.text','User')
        //Edit the data
        cy.get(':nth-child(1) > .MuiButtonBase-root > .MuiFormLabel-root').click()
        cy.get('input').eq(7).clear().type('New Test')
        cy.get('input').eq(8).clear().type('New Auto')
        cy.get('input').eq(9).clear().type('2345432345111')
        cy.get('input').eq(10).clear().type('9090909090000')
        cy.get('input').eq(11).clear().type('My new address 2')
        cy.get('input').eq(12).clear().type('My new address 22')
        cy.get('input').eq(13).clear().type('My New City 2')
        cy.get('input').eq(14).clear().type('123123123')
        cy.get('input').eq(15).clear().type('2323')
        cy.get('input').eq(19).clear().type('New Developer')
        cy.get('input').eq(20).clear().type('New New Department')
        cy.get('input').eq(21).clear().type('No New New Supervisor')
        cy.get('input').eq(22).clear().type('555444')
        cy.get(':nth-child(2) > .MuiButtonBase-root > .MuiFormLabel-root').click()
        cy.get(':nth-child(1) > .MuiOutlinedInput-root > .MuiSelect-select').click()
        cy.get('[data-value="56"]').click({force:true})
        cy.get('.css-z7g8xj').click()
        //Check that the changes after editing are saved
        cy.get(':nth-child(1) > .MuiButtonBase-root > .MuiFormLabel-root').click()
        //cy.get('.css-kspudp > .MuiGrid-container').should('contain.text','Edit User')
        cy.get('.css-z7g8xj').should('contain.text','Save')
        cy.get('.css-1dnniyh').should('contain.text','Cancel')
        cy.get('.MuiGrid-direction-xs-column > :nth-child(2) > .MuiButton-root').should('contain.text','Resend Welcome Email')
        cy.get('.MuiGrid-direction-xs-column > :nth-child(3) > .MuiButton-root').should('contain.text','Reset Password')
        cy.get('input').eq(4).should('contain.value','testautocy+3@gmail.com')
        cy.get('input').eq(5).should('be.checked')
        cy.get('input').eq(3).should('not.have.class', 'Mui-checked')
        cy.contains('User is active').should('be.visible')
        cy.contains('User is locked').should('be.visible')
        cy.get('input').eq(7).should('contain.value','New Test')
        cy.get('input').eq(8).should('contain.value','New Auto')
        cy.get('input').eq(9).should('contain.value','2345432345111')
        cy.get('input').eq(10).should('contain.value','9090909090000')
        cy.get('input').eq(11).should('contain.value','My new address 2')
        cy.get('input').eq(12).should('contain.value','My new address 22')
        cy.get('input').eq(13).should('contain.value','My New City 2')
        cy.get('input').eq(14).should('contain.value','123123123')
        cy.get('input').eq(15).should('contain.value','2323')
        cy.get('input').eq(19).should('contain.value','New Developer')
        cy.get('input').eq(20).should('contain.value','New New Department')
        cy.get('input').eq(21).should('contain.value','No New New Supervisor')
        cy.get('input').eq(22).should('contain.value','555444')
        cy.get('body').click()
        cy.reload()
        cy.contains('testautocy+3@gmail.com').click()
        cy.get(':nth-child(1) > .MuiButtonBase-root > .MuiFormLabel-root').click()
        cy.get(':nth-child(3) > .MuiButtonBase-root > .MuiFormLabel-root').click()
        cy.get('.MuiTabs-flexContainer > :nth-child(2) > .MuiButtonBase-root').click({force:true})
        cy.get(':nth-child(1) > .MuiOutlinedInput-root > .MuiSelect-select').should('contain.text','Admin assign roles')
        cy.get('.css-z7g8xj').click()
        //Delete the user
        cy.get('.css-10v05w1 > .MuiGrid-container > .css-1wxaqej > .MuiCheckbox-root > .PrivateSwitchBase-input').click()
        cy.get('[aria-label="Delete"] > .MuiButton-root').click()
        cy.get('.MuiDialogContent-root > .MuiTypography-root').should('contain.text','Are you sure you want to delete this user?')
        cy.contains('Delete User').click()
        cy.get('.css-1q77095 > .MuiTypography-root').click()
        cy.wait(5000)


    })
    after(()=>{
        cy.clearAllCookies()
        cy.clearAllLocalStorage()
    })
})