import {loginPage} from "../../support/pageObject/loginPage";

describe('TestDeviceAddEditDelete', () => {
    beforeEach(() => {
        loginPage.openLoginPage()
        loginPage.inputUser()
        loginPage.inputPass()
        loginPage.clickLoginButton()
        loginPage.acceptCoockies()
    })

    it('Add a Device', () => {
//The main page should be visible
        cy.get('.css-czc5e9 > :nth-child(1) > .MuiGrid-item > .MuiButtonBase-root').click()
        cy.get('[href="/assets"] > .MuiGrid-root > .MuiTypography-root').click()
        cy.get('.css-1d7v3j3 > .MuiGrid-item > .MuiButton-root').click()
        //Choose Assets -> Accounts
        //Automation account should be visible
        cy.get('.MuiList-root > [tabindex="0"]').click()
        //Choose Device tab
        cy.get(':nth-child(4) > :nth-child(4) > .css-1q2ebru > .css-17eim5l').click()
        cy.get('.MuiTabs-flexContainer > :nth-child(3) > .MuiButtonBase-root').click()
        cy.get('[aria-label="Add"] > .MuiButtonBase-root').should('be.visible')
        cy.get('[aria-label="Import"] > .MuiButtonBase-root').should('be.visible')
        cy.get('[aria-label="Export"] > .MuiButtonBase-root').should('be.visible')
        cy.get('[aria-label="Columns"] > .MuiButtonBase-root').should('be.visible')
        cy.get('[aria-label="Refresh"] > .MuiButtonBase-root').should('be.visible')
        cy.get('[aria-label="Add"] > .MuiButtonBase-root').click()
        //Check all the fields
        cy.get('.css-kspudp > .MuiGrid-container').should('contain.text','Add Device')
        cy.get('.css-1dnniyh').should('contain.text','Cancel')
        cy.get('.MuiGrid-grid-xs-12 > .MuiGrid-direction-xs-column > .MuiGrid-root > :nth-child(1) > .MuiTypography-root').should('contain.text','Active')
        cy.get('.MuiGrid-direction-xs-column > .MuiGrid-root > :nth-child(2) > .MuiTypography-root').should('contain.text','V.I.P')
        cy.get('.MuiGrid-direction-xs-column > .MuiGrid-root > :nth-child(3) > .MuiTypography-root').should('contain.text','Call Capable')
        cy.get('.MuiGrid-root > :nth-child(4) > .MuiTypography-root').should('contain.text','Simple Asset')
        cy.get('.MuiGrid-grid-xs-12 > .MuiGrid-direction-xs-column > .MuiGrid-root > :nth-child(1)').should('not.have.class', 'Mui-checked')
        cy.get('.MuiGrid-grid-xs-12 > .MuiGrid-direction-xs-column > .MuiGrid-root > :nth-child(2)').should('not.have.class', 'Mui-checked')
        cy.get('.MuiGrid-grid-xs-12 > .MuiGrid-direction-xs-column > .MuiGrid-root > :nth-child(3)').should('not.have.class', 'Mui-checked')
        cy.get('.MuiGrid-grid-xs-12 > .MuiGrid-direction-xs-column > .MuiGrid-root > :nth-child(4)').should('not.have.class', 'Mui-checked')
        cy.get(':nth-child(2) > .MuiGrid-spacing-xs-1 > :nth-child(2) > .MuiTypography-root').should('contain.text','Location Information')
        cy.get(':nth-child(2) > .MuiGrid-spacing-xs-1 > .css-m9a6wi > .MuiTypography-root').should('contain.text','Use these fields to specify the physical location of the device.')
        cy.get(':nth-child(2) > .MuiGrid-wrap-xs-nowrap > .MuiGrid-container > :nth-child(1) > .MuiFormControl-root > .MuiOutlinedInput-root > .MuiSelect-select').should('contain.text','Automation Account')
        cy.get('legend').eq(3).should('contain.text','Account')
        cy.get('legend').eq(4).should('contain.text','Location')
        cy.get('legend').eq(5).should('contain.text','Room')
        cy.get(':nth-child(3) > .MuiGrid-spacing-xs-1 > :nth-child(2) > .MuiTypography-root').should('contain.text','Device Model')
        cy.get(':nth-child(3) > .MuiGrid-spacing-xs-1 > .css-m9a6wi > .MuiTypography-root').should('contain.text','Use these fields to select the model of your device.')
        cy.get('legend').eq(6).should('contain.text','Type')
        cy.get('legend').eq(7).should('contain.text','Category')
        cy.get('legend').eq(8).should('contain.text','Manufacturer')
        cy.get('legend').eq(9).should('contain.text','Model')
        cy.get(':nth-child(4) > .MuiGrid-spacing-xs-1 > :nth-child(2) > .MuiTypography-root').should('contain.text','Monitoring')
        cy.get(':nth-child(4) > .MuiGrid-spacing-xs-1 > .css-m9a6wi > .MuiTypography-root').should('contain.text','Use these fields to determine how the device should be monitored.')
        cy.get('legend').eq(10).should('contain.text','Monitoring Service')
        cy.get('legend').eq(11).should('contain.text','Monitoring Source')
        cy.get('legend').eq(12).should('contain.text','Monitoring Proxy')
        cy.get(':nth-child(5) > .MuiGrid-spacing-xs-1 > :nth-child(2) > .MuiTypography-root').should('contain.text','Network')
        cy.get(':nth-child(5) > .MuiGrid-spacing-xs-1 > .css-m9a6wi > .MuiTypography-root').should('contain.text','Use these fields to enter the appropriate network address for the device.')
        cy.get('legend').eq(13).should('contain.text','Management Address')
        cy.get('legend').eq(14).should('contain.text','Local IP Address')
        cy.get('legend').eq(15).should('contain.text','Device Management URL')
        cy.get(':nth-child(6) > .MuiGrid-spacing-xs-1 > :nth-child(2) > .MuiTypography-root').should('contain.text','Device Unique Identifiers')
        cy.get(':nth-child(6) > .MuiGrid-spacing-xs-1 > .css-m9a6wi > .MuiTypography-root').should('contain.text','Use these fields to specify any UUID of your devices. In the case of monitoring via DMCA, at least one field is required.')
        cy.get('legend').eq(16).should('contain.text','Serial Number')
        cy.get('legend').eq(17).should('contain.text','MAC Address')
        cy.get('legend').eq(18).should('contain.text','Third Party ID')
        cy.get(':nth-child(7) > .MuiGrid-spacing-xs-1 > :nth-child(2) > .MuiTypography-root').should('contain.text','Device Information')
        cy.get(':nth-child(7) > .MuiGrid-spacing-xs-1 > .css-m9a6wi > .MuiTypography-root').should('contain.text','Use these fields to specify any device level information which may be beneficial to know.')
        cy.get('legend').eq(19).should('contain.text','Software Version')
        cy.get('legend').eq(20).should('contain.text','Operating System')
        cy.get(':nth-child(8) > .MuiGrid-spacing-xs-1 > :nth-child(2) > .MuiTypography-root').should('contain.text','Expiration Dates')
        cy.get(':nth-child(8) > .MuiGrid-spacing-xs-1 > .css-m9a6wi > .MuiTypography-root').should('contain.text','Use these fields to select expiration dates for your device. These can create tickets prior to reaching these dates.')
        cy.get('legend').eq(21).should('contain.text','Lease Expiration')
        cy.get('legend').eq(22).should('contain.text','Manufacturer Warranty Expiration')
        cy.get(':nth-child(9) > .MuiGrid-spacing-xs-1 > :nth-child(2) > .MuiTypography-root').should('contain.text','Additional Information')
        cy.get(':nth-child(9) > .MuiGrid-spacing-xs-1 > .css-m9a6wi > .MuiTypography-root').should('contain.text','Use these fields to select any further miscellaneous information about the device.')
        cy.get('legend').eq(23).should('contain.text','Configuration Item ID')
        cy.get('legend').eq(24).should('contain.text','Customer Cost Center ID')
        cy.get('.css-1jcxqcp > .MuiFormLabel-root').should('contain.text','Management Interface')
        cy.get('.css-4st0sz > .MuiGrid-container > .css-xpl8co').should('contain.text','Protocol')
        cy.get('th').eq(7).should('contain.text','Secure')
        cy.get('th').eq(8).should('contain.text','Username')
        cy.get('th').eq(9).should('contain.text','Password')
        cy.get('th').eq(10).should('contain.text','Local Port')
        cy.get('th').eq(11).should('contain.text','Remote Port')
        cy.get(':nth-child(1) > :nth-child(1) > .css-166ooic > .css-17eim5l > .MuiFormControlLabel-root > .MuiTypography-root').should('contain.text','HTTP')
        cy.get(':nth-child(2) > :nth-child(1) > .css-166ooic > .css-17eim5l > .MuiFormControlLabel-root > .MuiTypography-root').should('contain.text','SSH')
        cy.get(':nth-child(3) > :nth-child(1) > .css-166ooic > .css-17eim5l > .MuiFormControlLabel-root > .MuiTypography-root').should('contain.text','TELNET')
        //Add the Device data
        cy.get('input').eq(16).type('AAA Test Auto')
        cy.get('input').eq(17).click()
        cy.get(':nth-child(2) > .MuiGrid-wrap-xs-nowrap > .MuiGrid-container > :nth-child(2) > .MuiFormControl-root > .MuiOutlinedInput-root > .MuiSelect-select').click()
        cy.get('.MuiList-root > [tabindex="0"]').click({force:true})
        cy.get(':nth-child(2) > .MuiGrid-wrap-xs-nowrap > .MuiGrid-container > :nth-child(3) > .MuiFormControl-root > .MuiOutlinedInput-root > .MuiSelect-select').click()
        cy.get('[data-value="11b759ed-6491-46c8-9998-f7b72dc19547"]').click({force:true})
        cy.get(':nth-child(3) > .MuiGrid-wrap-xs-nowrap > .MuiGrid-container > :nth-child(1) > .MuiFormControl-root > .MuiOutlinedInput-root > .MuiSelect-select').click()
        cy.get('[data-value="Codecs"]').click({force:true})
        cy.get(':nth-child(3) > .MuiGrid-wrap-xs-nowrap > .MuiGrid-container > :nth-child(2) > .MuiFormControl-root > .MuiOutlinedInput-root > .MuiSelect-select').click()
        cy.get('.Mui-focusVisible').click({force:true})
        cy.get(':nth-child(3) > .MuiGrid-wrap-xs-nowrap > .MuiGrid-container > :nth-child(3) > .MuiFormControl-root > .MuiOutlinedInput-root > .MuiSelect-select').click()
        cy.get('[data-value="Cisco"]').click({force:true})
        cy.get(':nth-child(3) > .MuiGrid-wrap-xs-nowrap > .MuiGrid-container > :nth-child(4) > .MuiFormControl-root > .MuiOutlinedInput-root > .MuiSelect-select').click()
        cy.get('[data-value="DX80"]').click({force:true})
        cy.get(':nth-child(4) > .MuiGrid-wrap-xs-nowrap > .MuiGrid-container > :nth-child(1) > .MuiFormControl-root > .MuiOutlinedInput-root > .MuiSelect-select').click()
        cy.get('[data-value="All"]').click({force:true})
        cy.get(':nth-child(4) > .MuiGrid-wrap-xs-nowrap > .MuiGrid-container > :nth-child(2) > .MuiFormControl-root > .MuiOutlinedInput-root > .MuiSelect-select').click()
        cy.get('[data-value="Symphony Direct"]').click({force:true})
        cy.get('input').eq(32).type('172.31.254.145')
        cy.get(':nth-child(10) > .MuiGrid-wrap-xs-nowrap > .MuiGrid-container > :nth-child(1) > .MuiFormControl-root > .MuiOutlinedInput-root > .MuiSelect-select').click()
        cy.get('[data-value="SIP Only"]').click({force:true})
        cy.get(':nth-child(10) > .MuiGrid-wrap-xs-nowrap > .MuiGrid-container > :nth-child(2) > .MuiFormControl-root > .MuiOutlinedInput-root > .MuiSelect-select').click()
        cy.get('[data-value="Auto"]').click({force:true})
        cy.get('input').eq(48).type('172.31.254.64')
        cy.get('input').eq(50).type('7771991045@nh.vnoc1.com')
        cy.get('input').eq(51).type('NH-DX80-4@nh.vnoc1.com')
        cy.get(':nth-child(1) > :nth-child(1) > .css-166ooic > .css-17eim5l').click()
        cy.get(':nth-child(2) > :nth-child(1) > .css-166ooic > .css-17eim5l').click()
        cy.get('input').eq(55).type('admin')
        cy.get('input').eq(56).type('1213')
        cy.get('input').eq(57).type('443')
        cy.get('input').eq(61).type('admin')
        cy.get('input').eq(62).type('1213')
        cy.get('input').eq(63).type('22')
        cy.wait(5000)
        cy.get('.css-z7g8xj > .MuiTypography-root').click()
        cy.get(':nth-child(1) > .css-1g6tcg4 > .css-10v05w1 > .MuiGrid-container > .css-9y94a1 > .jss143 > .jss144 > .MuiButton-root').should('contain.text','AAA Test Auto')
        cy.get('.css-1w1y9ry').should('contain.text','Success')
        cy.get('[direction="up"] > .MuiPaper-root').should('contain.text','The device was successfully added')
        //Edit the Device data
        cy.get(':nth-child(1) > .css-1g6tcg4 > .css-10v05w1 > .MuiGrid-container > .css-9y94a1 > .jss143 > .jss144 > .MuiButton-root').click()
        cy.wait(5000)
        cy.get(':nth-child(17) > span[aria-label=""] > .MuiButton-root').click()

        //Check that all fields are filled correctly
        cy.get('.css-kspudp > .MuiGrid-container').should('contain.text','Edit Device')
        cy.get('.css-z7g8xj').should('contain.text','Save')
        cy.get('.css-1dnniyh').should('contain.text','Cancel')
        cy.get('input').eq(5).should('be.checked')
        cy.get('input').eq(6).should('not.have.class', 'Mui-checked')
        cy.get('input').eq(4).should('contain.value','AAA Test Auto')
        //cy.get('input').eq(10).should('contain.value','Automation Account')
        //cy.get('input').eq(11).should('contain.text','Automation Location')
        //cy.get('input').eq(11).should('contain.value','Automation Room')
        //cy.get('input').eq(11).should('contain.value','My address 1')
        //cy.get('input').eq(12).should('contain.value','My address 2')
        //cy.get('input').eq(13).should('contain.value','My City 1')
        //cy.get('input').eq(14).should('contain.value','123')
        //cy.get('input').eq(15).should('contain.value','2')
        //cy.get('input').eq(19).should('contain.value','Developer')
        //cy.get('input').eq(20).should('contain.value','New Department')
        //cy.get('input').eq(21).should('contain.value','No New Supervisor')
        cy.get('input').eq(36).should('contain.value','172.31.254.64')
        cy.get('input').eq(38).should('contain.value','7771991045@nh.vnoc1.com')
        cy.get('input').eq(39).should('contain.value','NH-DX80-4@nh.vnoc1.com')
        cy.get('input').eq(43).should('contain.value','admin')
        cy.get('input').eq(44).should('contain.value','1213')
        cy.get('input').eq(45).should('contain.value','443')
        cy.get('input').eq(49).should('contain.value','admin')
        cy.get('input').eq(50).should('contain.value','1213')
        cy.get('input').eq(51).should('contain.value','22')

        //Edit the data
        cy.get('input').eq(36).clear().type('172.31.254.65')
        cy.get('input').eq(38).clear().type('77771991045@nh.vnoc1.com')
        cy.get('input').eq(39).clear().type('1NH-DX80-4@nh.vnoc1.com')
        cy.get('input').eq(43).clear().type('admin1')
        cy.get('input').eq(44).clear().type('121313')
        cy.get('input').eq(45).clear().type('4433')
        cy.get('input').eq(49).clear().type('admin2')
        cy.get('input').eq(50).clear().type('121313')
        cy.get('input').eq(51).clear().type('222')
        cy.get('.css-z7g8xj').click()

        //Check that the data is saved
        cy.get('.css-kspudp > .MuiGrid-container').should('contain.text','Edit Device')
        cy.get('.css-z7g8xj').should('contain.text','Save')
        cy.get('.css-1dnniyh').should('contain.text','Cancel')
        cy.get('input').eq(5).should('be.checked')
        cy.get('input').eq(6).should('not.have.class', 'Mui-checked')
        cy.get('input').eq(4).should('contain.value','AAA Test Auto')
        cy.get('input').eq(36).should('contain.value','172.31.254.65')
        cy.get('input').eq(38).should('contain.value','77771991045@nh.vnoc1.com')
        cy.get('input').eq(39).should('contain.value','1NH-DX80-4@nh.vnoc1.com')
        cy.get('input').eq(43).should('contain.value','admin1')
        cy.get('input').eq(44).should('contain.value','121313')
        cy.get('input').eq(45).should('contain.value','4433')
        cy.get('input').eq(49).should('contain.value','admin2')
        cy.get('input').eq(50).should('contain.value','121313')
        cy.get('input').eq(51).should('contain.value','222')
        cy.get('.css-1dnniyh').click({force:true})
        cy.wait(5000)
        cy.get('.MuiGrid-root > .MuiButton-root').click()
        cy.get(':nth-child(1) > .css-1g6tcg4 > .css-10v05w1 > .jss258 > .jss259 > .MuiButton-root').should('contain.text','AAA Test Auto')
        cy.get(':nth-child(3) > .MuiButtonBase-root > .MuiFormLabel-root').click()
        cy.get(':nth-child(1) > .css-1g6tcg4 > .css-10v05w1 > .MuiGrid-container > .css-1wxaqej > .MuiCheckbox-root > .PrivateSwitchBase-input').click()
        cy.get('[aria-label="Delete"] > .MuiButton-root').click()
        cy.get('button').contains('Delete Device').click()
        cy.get(':nth-child(1) > .css-1g6tcg4 > .css-10v05w1 > .MuiGrid-container > .css-1wxaqej > .MuiCheckbox-root > .PrivateSwitchBase-input').should('not.contains.text','1')
        cy.reload()

    })
    after(()=>{
        cy.clearAllCookies()
        cy.clearAllLocalStorage()
    })
})