import {loginPage} from "../../support/pageObject/loginPage";

describe('TestLocationAddEditDelete', () => {
    beforeEach(() => {
        loginPage.openLoginPage()
        loginPage.inputUser()
        loginPage.inputPass()
        loginPage.clickLoginButton()
        loginPage.acceptCoockies()
    })

    it('Create a Location', () => {
//The main page should be visible
        cy.get('.css-czc5e9 > :nth-child(1) > .MuiGrid-item > .MuiButtonBase-root').click()
        cy.get('[href="/assets"] > .MuiGrid-root > .MuiTypography-root').click()
        cy.get('.css-1d7v3j3 > .MuiGrid-item > .MuiButton-root').click()
        //Choose Assets -> Accounts
        //Automation account should be visible
        cy.get('.MuiList-root > [tabindex="0"]').click()
        cy.get(':nth-child(4) > .css-1g6tcg4 > .css-10v05w1 > .jss88 > .jss89 > .MuiButton-root').should('be.visible')
        //Choose Location tab
        cy.get(':nth-child(4) > :nth-child(2) > .css-166ooic > .css-17eim5l').click()
        //Click Administration tab and check the visible icons
        cy.get('.MuiTabs-flexContainer > :nth-child(3) > .MuiButtonBase-root').click()
        cy.get('[aria-label="Add"] > .MuiButtonBase-root').should('be.visible')
        cy.get('[aria-label="Import"] > .MuiButtonBase-root').should('be.visible')
        cy.get('[aria-label="Export"] > .MuiButtonBase-root').should('be.visible')
        cy.get('[aria-label="Columns"] > .MuiButtonBase-root').should('be.visible')
        cy.get('[aria-label="Refresh"] > .MuiButtonBase-root').should('be.visible')
        //Check the hints
        cy.get('[aria-label="Add"] > .MuiButtonBase-root').trigger('mouseover')
        cy.get('.MuiTooltip-tooltip').should('contain.text','Add')
        cy.get('[aria-label="Add"] > .MuiButtonBase-root').trigger('mouseout')
        cy.get('[aria-label="Import"] > .MuiButtonBase-root').trigger('mouseover')
        cy.get('.MuiTooltip-tooltip').should('contain.text','Import')
        cy.get('[aria-label="Import"] > .MuiButtonBase-root').trigger('mouseout')
        cy.get('[aria-label="Export"] > .MuiButtonBase-root').trigger('mouseover')
        cy.get('.MuiTooltip-tooltip').should('contain.text','Export')
        cy.get('[aria-label="Export"] > .MuiButtonBase-root').trigger('mouseout')
        cy.get('[aria-label="Columns"] > .MuiButtonBase-root').trigger('mouseover')
        cy.get('.MuiTooltip-tooltip').should('contain.text','Columns')
        cy.get('[aria-label="Columns"] > .MuiButtonBase-root').trigger('mouseout')
        cy.get('[aria-label="Refresh"] > .MuiButtonBase-root').trigger('mouseover')
        cy.get('.MuiTooltip-tooltip').should('contain.text','Refresh')
        cy.get('[aria-label="Refresh"] > .MuiButtonBase-root').trigger('mouseout')
        //Click Add button
        //Check all the fields
        cy.get('[aria-label="Add"] > .MuiButtonBase-root').click()
        cy.get('.css-kspudp > .MuiGrid-container > .MuiTypography-body1').should('contain.text','Add Location')
        cy.get('.css-1dnniyh').should('contain.text','Cancel')
        cy.get('.css-g7ht58 > .MuiGrid-container > :nth-child(2) > :nth-child(2)').should('contain.text','Location is active')
        cy.get('input').eq(9).should('not.have.class', 'Mui-checked')
        cy.get('legend').eq(4).should('contain.text','Address 1')
        cy.get('legend').eq(5).should('contain.text','Address 2')
        cy.get('legend').eq(6).should('contain.text','City')
        cy.get('legend').eq(7).should('contain.text','State')
        cy.get('legend').eq(8).should('contain.text','Zip')
        cy.get('legend').eq(9).should('contain.text','Country')
        cy.get('legend').eq(10).should('contain.text','Timezone')
        cy.get('legend').eq(11).should('contain.text','Geo Location')
        //Add the data and save the Location
        cy.get('input').eq(8).type('1')
        cy.get('input').eq(9).click()
        cy.get('input').eq(11).type('Address address 1')
        cy.get('input').eq(12).type('Address address 2')
        cy.get('input').eq(13).type('City 1')
        cy.get('input').eq(14).type('1')
        cy.get('input').eq(15).type('2')
        cy.get('#mui-component-select-country').click()
        cy.get('[data-value="Antarctica"]').click()
        cy.wait(1000)
        cy.get('#mui-component-select-timeZone').click()
        cy.get('[data-value="(UTC-06:00) Central America"]').click()
        cy.wait(1000)
        cy.get('#mui-component-select-geoLocationAutomatic').click()
        cy.get('.MuiList-root > .Mui-selected').click()
        cy.wait(1000)
        cy.get('input').eq(19).type('My name')
        cy.get('input').eq(20).type('my email')
        cy.get('input').eq(21).type('my phone')
        cy.get('input').eq(22).type('https://chi-qa-ui.vnocsymphony.com/assets/locations?fromAccount=5e37f483-4e36-4059-8ede-429b4e4bab7f')
        cy.get('button').contains('Add').click()
        //At the Locations tab
        cy.get(':nth-child(1) > .css-1g6tcg4 > .css-10v05w1 > .MuiGrid-container > .css-9y94a1 > .jss140 > .jss141 > .MuiButton-root').should('contain.text','1')
        cy.get(':nth-child(1) > .css-1g6tcg4 > .css-10v05w1 > .MuiGrid-container > .css-9y94a1 > .jss140 > .jss141 > .MuiButton-root').click()
        //Edit location
        cy.wait(3000)
        cy.get(':nth-child(3) > span[aria-label=""] > .MuiButton-root').click()
        cy.wait(5000)
        cy.get('.MuiPaper-root > .MuiButtonBase-root > .css-mweiv9').click()
        //Check the saved data
        cy.get('input').eq(2).should('contain.value','1')
        cy.get('input').eq(4).should('contain.value','Address address 1')
        cy.get('input').eq(5).should('contain.value','Address address 2')
        cy.get('input').eq(6).should('contain.value','City 1')
        cy.get('input').eq(7).should('contain.value','1')
        cy.get('input').eq(8).should('contain.value','2')
        cy.get('input').eq(12).should('contain.value','My name')
        cy.get('input').eq(13).should('contain.value','my email')
        cy.get('input').eq(14).should('contain.value','my phone')
        cy.get('input').eq(15).should('contain.value','https://chi-qa-ui.vnocsymphony.com/assets/locations?fromAccount=5e37f483-4e36-4059-8ede-429b4e4bab7f')
        //Edit the data
        cy.get('input').eq(4).clear().type('New Address address 1')
        cy.get('input').eq(5).clear().type('New Address address 2')
        cy.get('input').eq(6).clear().type('City 2')
        cy.get('input').eq(7).clear().type('12')
        cy.get('input').eq(8).clear().type('23')
        cy.get('input').eq(12).clear().type('My New name')
        cy.get('input').eq(13).clear().type('my New email')
        cy.get('input').eq(14).clear().type('my New phone')
        cy.get('input').eq(15).clear().type('https://chi-qa-ui.vnocsymphony.com')
        cy.get('button').contains('Save').click()
        cy.wait(1000)
        cy.get('.MuiPaper-root > .MuiButtonBase-root > .css-mweiv9').click()
        cy.get('input').eq(4).should('contain.value','1')
        cy.get('input').eq(4).should('contain.value','New Address address 1')
        cy.get('input').eq(5).should('contain.value','New Address address 2')
        cy.get('input').eq(6).should('contain.value','City 2')
        cy.get('input').eq(7).should('contain.value','12')
        cy.get('input').eq(8).should('contain.value','23')
        cy.get('input').eq(12).should('contain.value','My New name')
        cy.get('input').eq(13).should('contain.value','my New email')
        cy.get('input').eq(14).should('contain.value','my New phone')
        cy.get('input').eq(15).should('contain.value','https://chi-qa-ui.vnocsymphony.com')
        cy.get('button').contains('Cancel').click()
        //Delete the Location
        cy.get('.MuiGrid-root > .MuiButton-root').click()
        cy.wait(1000)
        cy.get('.MuiGrid-root > .MuiButton-root').click()
        //Administration tab
        cy.get(':nth-child(3) > .MuiButtonBase-root > .MuiFormLabel-root').click()
        cy.get(':nth-child(1) > .css-1g6tcg4 > .css-10v05w1 > .MuiGrid-container > .css-1wxaqej > .MuiCheckbox-root > .PrivateSwitchBase-input').click()
        cy.get('[aria-label="Delete"] > .MuiButton-root').click()
        cy.get('button').contains('Delete Location').click()
        cy.get(':nth-child(1) > .css-1g6tcg4 > .css-10v05w1 > .MuiGrid-container > .css-9y94a1 > .jss295 > .jss296 > .MuiButton-root').should('not.contains.text','1')


    })
    after(()=>{
        cy.clearAllCookies()
        cy.clearAllLocalStorage()
    })
})