import {loginPage} from "../../support/pageObject/loginPage";

describe('TestRoomsAddEditDelete', () => {
    beforeEach(() => {
        loginPage.openLoginPage()
        loginPage.inputUser()
        loginPage.inputPass()
        loginPage.clickLoginButton()
        loginPage.acceptCoockies()
    })

    it('Create a Room', () => {
//The main page should be visible
        cy.get('.css-czc5e9 > :nth-child(1) > .MuiGrid-item > .MuiButtonBase-root').click()
        cy.get('[href="/assets"] > .MuiGrid-root > .MuiTypography-root').click()
        cy.get('.css-1d7v3j3 > .MuiGrid-item > .MuiButton-root').click()
        //Choose Assets -> Accounts
        //Automation account should be visible
        cy.get('.MuiList-root > [tabindex="0"]').click()
        cy.get(':nth-child(4) > .css-1g6tcg4 > .css-10v05w1 > .jss88 > .jss89 > .MuiButton-root').should('be.visible')
        //Choose Room tab
        cy.get(':nth-child(4) > :nth-child(3) > .css-1q2ebru > .css-17eim5l').click()
        //Click Administration tab and check the visible icons
        cy.get('.MuiTabs-flexContainer > :nth-child(3) > .MuiButtonBase-root').click()
        cy.get('[aria-label="Add"] > .MuiButtonBase-root').should('be.visible')
        cy.get('[aria-label="Import"] > .MuiButtonBase-root').should('be.visible')
        cy.get('[aria-label="Export"] > .MuiButtonBase-root').should('be.visible')
        cy.get('[aria-label="Columns"] > .MuiButtonBase-root').should('be.visible')
        cy.get('[aria-label="Refresh"] > .MuiButtonBase-root').should('be.visible')
        //Click Add button
        cy.get('[aria-label="Add"] > .MuiButtonBase-root').click()
        //Check all the elements at the page
        cy.get('.css-kspudp > .MuiGrid-container > .MuiTypography-body1').should('contain.text','Add Room')
        cy.get('.css-1dnniyh').should('contain.text','Cancel')
        cy.get('.MuiGrid-item > .MuiGrid-root > .MuiTabs-root > .MuiTabs-scroller > .MuiTabs-flexContainer > :nth-child(1) > .MuiButtonBase-root > .MuiFormLabel-root').should('contain.text','Information *')
        cy.get('.MuiGrid-item > .MuiGrid-root > .MuiTabs-root > .MuiTabs-scroller > .MuiTabs-flexContainer > :nth-child(2) > .MuiButtonBase-root > .MuiFormLabel-root').should('contain.text', 'Visibility')
        cy.get('.MuiGrid-grid-xs-4 > .MuiFormControlLabel-root > .MuiTypography-root').should('contain.text','Show only required fields')
        //Check that the checkboxes are available and unchecked
        cy.get('input').eq(15).should('not.have.class', 'Mui-checked')
        cy.get('input').eq(16).should('not.have.class', 'Mui-checked')
        cy.get('input').eq(17).should('not.have.class', 'Mui-checked')
        cy.get('input').eq(18).should('not.have.class', 'Mui-checked')
        cy.get('input').eq(19).should('not.have.class', 'Mui-checked')
        cy.get(':nth-child(4) > :nth-child(1) > .MuiTypography-root').should('contain.text', 'Managed')
        cy.get(':nth-child(4) > :nth-child(2) > .MuiTypography-root').should('contain.text', 'Active')
        cy.get(':nth-child(4) > :nth-child(3) > .MuiTypography-root').should('contain.text', 'Public')
        cy.get(':nth-child(4) > :nth-child(4) > .MuiTypography-root').should('contain.text', 'VIP')
        cy.get('[title=""] > .MuiTypography-root').should('contain.text','Certified')
        //Check the elements and texts are visible at the main part
        cy.get(':nth-child(2) > .MuiGrid-spacing-xs-1 > :nth-child(2) > .MuiTypography-root').should('contain.text','Location Contact')
        cy.get(':nth-child(2) > .MuiGrid-spacing-xs-1 > .css-m9a6wi > .MuiTypography-root').should('contain.text','These fields are inherited by the contact set at Location level, this makes them read only.')
        cy.contains('Contact Name')
        cy.contains('Contact Email')
        cy.contains('Contact Phone')
        cy.get(':nth-child(3) > .MuiGrid-spacing-xs-1 > :nth-child(2) > .MuiTypography-root').should('contain.text','Room Contact')
        cy.get(':nth-child(3) > .MuiGrid-spacing-xs-1 > .css-m9a6wi > .MuiTypography-root').should('contain.text','Use these fields to specify the contact for the room.')
        cy.get('legend').eq(5).should('contain.text','Contact Name')
        cy.get('legend').eq(6).should('contain.text','Contact Email')
        cy.get('legend').eq(7).should('contain.text','Contact Phone')
        cy.get('legend').eq(8).should('contain.text','Contact URL')
        cy.get(':nth-child(4) > .MuiGrid-spacing-xs-1 > :nth-child(2) > .MuiTypography-root').should('contain.text','Room Unique Identifiers')
        cy.get(':nth-child(4) > .MuiGrid-spacing-xs-1 > .css-m9a6wi > .MuiTypography-root').should('contain.text','Use these fields to specify any UUID of your room.')
        cy.get('legend').eq(9).should('contain.text','Configuration Item ID')
        cy.get('legend').eq(10).should('contain.text','Exchange ID')
        cy.get(':nth-child(5) > .MuiGrid-spacing-xs-1 > :nth-child(2) > .MuiTypography-root').should('contain.text','Room Information')
        cy.get(':nth-child(5) > .MuiGrid-spacing-xs-1 > .css-m9a6wi > .MuiTypography-root').should('contain.text','Use these fields to specify any room level information which may be beneficial to know.')
        cy.get('legend').eq(11).should('contain.text','Room Type')
        cy.get('legend').eq(12).should('contain.text','Scheduling Option')
        cy.get('.MuiGrid-wrap-xs-nowrap > .MuiGrid-container > :nth-child(2) > .MuiFormControl-root > .MuiOutlinedInput-root > .MuiSelect-select').click()
        cy.get('.MuiList-root > [tabindex="0"]').should('contains.text','None')
        cy.get('[data-value="VC Scheduling"]').should('contains.text','VC Scheduling')
        cy.get('[data-value="Room Only Scheduling"]').should('contains.text','Room Only Scheduling')
        cy.get('body').click()
        cy.get('legend').eq(13).should('contain.text','Room Number')
        cy.get('legend').eq(14).should('contain.text','Room Capacity')
        cy.get(':nth-child(6) > .MuiGrid-spacing-xs-1 > :nth-child(2) > .MuiTypography-root').should('contain.text','Expiration Date')
        cy.get(':nth-child(6) > .MuiGrid-spacing-xs-1 > .css-m9a6wi > .MuiTypography-root').should('contain.text','Use these fields to select dates for your room. These can create tickets prior to reaching these dates.')
        cy.get('legend').eq(15).should('contain.text','Service Contract Expiration')
        cy.get(':nth-child(7) > .MuiGrid-spacing-xs-1 > :nth-child(2) > .MuiTypography-root').should('contain.text','Room URLs')
        cy.get(':nth-child(7) > .MuiGrid-spacing-xs-1 > .css-m9a6wi > .MuiTypography-root').should('contain.text','Use these fields to assist with ease-of-access from the Room Detail View.')
        cy.get('legend').eq(16).should('contain.text','Room Camera URL')
        cy.get('legend').eq(17).should('contain.text','Control Panel URL')

        //Add Data for the New Room
        cy.get('input').eq(12).type('1')
        cy.get('.css-14xsf0m > .MuiGrid-container > :nth-child(2) > .MuiFormControl-root > .MuiOutlinedInput-root > .MuiSelect-select').click()
        cy.get('.MuiList-root > .Mui-selected').click()
        cy.get(':nth-child(3) > .MuiFormControl-root > .MuiOutlinedInput-root > .MuiSelect-select').click()
        cy.get('.MuiList-root > [tabindex="0"]').click()
        cy.get('input').eq(16).check()
        cy.get('input').eq(17).check()
        cy.get(':nth-child(3) > .MuiGrid-spacing-xs-1 > :nth-child(2) > .MuiTypography-root').should('contain.text','Room Contact')
        cy.get(':nth-child(3) > .MuiGrid-spacing-xs-1 > .css-m9a6wi > .MuiTypography-root').should('contain.text','Use these fields to specify the contact for the room.')
        cy.get('input').eq(21).type('Elena')
        cy.get('input').eq(22).type('Test Auto')
        cy.get('input').eq(23).type('emailcontact.test')
        cy.get('input').eq(24).type('2342234')
        cy.get(':nth-child(4) > .MuiGrid-spacing-xs-1 > :nth-child(2) > .MuiTypography-root').should('contain.text','Room Unique Identifiers')
        cy.get(':nth-child(4) > .MuiGrid-spacing-xs-1 > .css-m9a6wi > .MuiTypography-root').should('contain.text','Use these fields to specify any UUID of your room.')
        cy.get('input').eq(25).type('4567345678')
        cy.get('input').eq(26).type('23232332332')
        cy.get(':nth-child(5) > .MuiGrid-spacing-xs-1 > :nth-child(2) > .MuiTypography-root').should('contain.text','Room Information')
        cy.get(':nth-child(5) > .MuiGrid-spacing-xs-1 > .css-m9a6wi > .MuiTypography-root').should('contain.text','Use these fields to specify any room level information which may be beneficial to know.')
        cy.get(':nth-child(1) > .MuiFormControl-root > .MuiOutlinedInput-root > .MuiSelect-select').click()
        cy.get('[data-value="Audio"]').click()
        cy.get('legend').eq(12).should('contain.text','Scheduling Option')
        cy.get('.MuiGrid-wrap-xs-nowrap > .MuiGrid-container > :nth-child(2) > .MuiFormControl-root > .MuiOutlinedInput-root > .MuiSelect-select').click()
        cy.get('[data-value="Room Only Scheduling"]').click()
        cy.get('body').click()
        cy.get('input').eq(29).type('1')
        cy.get('input').eq(30).type('123')
        cy.get('legend').eq(15).should('contain.text','Service Contract Expiration')
        cy.get('.MuiInputAdornment-root > .MuiButtonBase-root').click()
        cy.get('.css-1lkrp06 > .MuiButtonBase-root').click()
        cy.get(':nth-child(126) > .PrivatePickersYear-yearButton').click()
        cy.get(':nth-child(1) > :nth-child(5) > .MuiButtonBase-root').click()
        cy.wait(1000)
        cy.get('body').click()
        cy.wait(2000)
        cy.get('input').eq(32).type('https://chi-qa-ui.vnocsymphony.com/assets/rooms?fromAccount=5e37f483-4e36-4059-8ede-429b4e4bab7f')
        cy.get('input').eq(33).type('https://chi-qa-ui.vnocsymphony.com/assets/rooms?fromAccount=5e37f483-4e36-4059-8ede-429b4e4bab7f')
        cy.wait(2000)
        //Save the Room
        cy.get('button').contains('Add').click()
        //Check that all the data is saved
        cy.get(':nth-child(1) > .css-1g6tcg4 > .css-10v05w1 > .MuiGrid-container > .css-9y94a1 > .jss133 > .jss134 > .MuiButton-root').click()
        cy.get(':nth-child(7) > span[aria-label=""] > .MuiButton-root').click()
        cy.get('input').eq(3).should('contain.value','1')
        cy.get('input').eq(5).should('contain.value', 'on')
        cy.get('input').eq(6).should('contain.value', 'on')
        cy.get('input').eq(11).should('contain.value', 'Elena')
         cy.get('input').eq(12).should('contain.value','Test Auto')
        cy.get('input').eq(13).should('contain.value','emailcontact.test')
        cy.get('input').eq(14).should('contain.value','2342234')
        //cy.get('input').eq(15).should('contain.value','345678')
        cy.get('input').eq(15).should('contain.value','4567345678')
        cy.get('input').eq(16).should('contain.value','23232332332')
        cy.get('input').eq(19).should('contain.value','1')
        cy.get('input').eq(20).should('contain.value','123')
        //Edit data
        cy.get('input').eq(5).click()
        cy.get('input').eq(7).click()
        cy.get('input').eq(11).clear().type('Elena test')
        cy.get('input').eq(12).clear().type(' New Test Auto')
        cy.get('input').eq(13).clear().type('Newemailcontact.test')
        cy.get('input').eq(14).clear().type('2342234000')
        cy.get('input').eq(15).clear().type('345678000')
        cy.get('input').eq(16).clear().type('4567345678000')
        //cy.get('input').eq(17).clear().type('23232332332555')
        cy.wait(1000)
        cy.get('input').eq(19).clear().type('134')
        cy.get('input').eq(20).clear().type('123123')
        cy.wait(1000)
        cy.get('button').contains('Save').click()
        //Check that the changes are saved
        cy.get(':nth-child(7) > span[aria-label=""] > .MuiButton-root').click()
        cy.get('input').eq(3).should('contain.value','1')
        cy.get('input').eq(6).should('contain.value', 'on')
        cy.get('input').eq(7).should('contain.value', 'on')
        cy.get('input').eq(11).should('contain.value', 'Elena test')
        cy.get('input').eq(12).should('contain.value','New Test Auto')
        cy.get('input').eq(13).should('contain.value','Newemailcontact.test')
        cy.get('input').eq(14).should('contain.value','2342234000')
        cy.get('input').eq(15).should('contain.value','345678000')
        cy.get('input').eq(16).should('contain.value','4567345678000')
        //cy.get('input').eq(17).should('contain.value','23232332332555')
        cy.get('input').eq(19).should('contain.value','134')
        cy.get('input').eq(20).should('contain.value','123123')
        cy.get('button').contains('Cancel').click()
        cy.wait(1000)
        //Delete the Room
        cy.get('.MuiGrid-root > .MuiButton-root').click()
        cy.get(':nth-child(3) > .MuiButtonBase-root > .MuiFormLabel-root').click()
        cy.get(':nth-child(1) > .css-1g6tcg4 > .css-10v05w1 > .MuiGrid-container > .css-1wxaqej > .MuiCheckbox-root > .PrivateSwitchBase-input').click()
        cy.get('[aria-label="Delete"] > .MuiButton-root').click()
        cy.get('button').contains('Delete Room').click()
        cy.get(':nth-child(1) > .css-1g6tcg4 > .css-10v05w1 > .MuiGrid-container > .css-1wxaqej > .MuiCheckbox-root > .PrivateSwitchBase-input').should('not.contains.text','1')
        cy.reload()


    })
    after(()=>{
        cy.clearAllCookies()
        cy.clearAllLocalStorage()
    })
})